/**
 * UK place centroids and radius arithmetic.
 *
 * Location matching used to be a single `ILIKE '%town%'` against the advert's
 * raw location text, which meant a search for Manchester never saw a role
 * advertised in Salford or Trafford Park — three and two miles away — while a
 * search for "Bath" matched "Bathgate". Distance fixes both.
 *
 * The dataset is generated by `scripts/build-uk-places.mjs` and committed, so
 * nothing here performs a network request. See that script for provenance and
 * licensing.
 */

import dataset from "./uk-places.generated.json" with { type: "json" };

export type UkPlace = Readonly<{
  name: string;
  nation: "England" | "Scotland" | "Wales" | "Northern Ireland";
  latitude: number;
  longitude: number;
}>;

/** Radii offered to users, in miles. Bounded so no query can ask for the country. */
export const radiusOptions = [5, 10, 20, 30, 50] as const;
export type RadiusMiles = (typeof radiusOptions)[number];

export function isRadiusMiles(value: unknown): value is RadiusMiles {
  return radiusOptions.includes(value as RadiusMiles);
}

/**
 * Must stay identical to `normalise` in `scripts/build-uk-places.mjs` and to
 * `private.normalise_place_name` in the database.
 */
export function normalisePlaceName(value: string): string {
  return value
    .normalize("NFD")
    .replaceAll(/[̀-ͯ]/gu, "")
    .toLowerCase()
    .replaceAll(/[^a-z0-9]+/gu, " ")
    .trim();
}

const places: readonly UkPlace[] = Object.freeze(
  dataset.places.map((place) =>
    Object.freeze({
      name: place.name,
      nation: place.nation as UkPlace["nation"],
      latitude: place.latitude,
      longitude: place.longitude,
    }),
  ),
);

/**
 * Several names legitimately resolve to one settlement, and one name can
 * legitimately name two settlements — there is a Bangor in Gwynedd and another
 * in County Down. The index therefore maps a name to every place that carries
 * it rather than to one winner, and callers decide what to do with ambiguity.
 */
const byNormalisedName = new Map<string, UkPlace[]>();
for (const place of places) {
  const key = normalisePlaceName(place.name);
  const existing = byNormalisedName.get(key);
  if (existing) existing.push(place);
  else byNormalisedName.set(key, [place]);
}

export function allUkPlaces(): readonly UkPlace[] {
  return places;
}

/**
 * Resolves free text to the places it could mean.
 *
 * Job adverts write locations as prose — "Leeds, West Yorkshire (hybrid)",
 * "Manchester city centre" — so an exact match alone finds very little. An
 * exact match wins outright when there is one; otherwise the longest contained
 * place name wins, because "Newcastle upon Tyne" should beat "Newcastle" on a
 * string that contains both.
 */
export function resolveUkPlaces(text: string): readonly UkPlace[] {
  const normalised = normalisePlaceName(text);
  if (normalised.length === 0) return [];

  const exact = byNormalisedName.get(normalised);
  if (exact) return exact;

  let bestLength = 0;
  let best: UkPlace[] = [];
  for (const [name, candidates] of byNormalisedName) {
    if (name.length <= bestLength) continue;
    // Word-boundary containment, so "bath" does not match "bathgate" and "ely"
    // does not match "wembley".
    if (!new RegExp(`(^| )${escapeRegExp(name)}( |$)`, "u").test(normalised)) {
      continue;
    }
    bestLength = name.length;
    best = candidates;
  }
  return best;
}

function escapeRegExp(value: string): string {
  return value.replaceAll(/[.*+?^${}()|[\]\\]/gu, "\\$&");
}

const earthRadiusMiles = 3958.8;

/** Great-circle distance in miles. */
export function distanceMiles(
  from: { latitude: number; longitude: number },
  to: { latitude: number; longitude: number },
): number {
  const toRadians = (degrees: number) => (degrees * Math.PI) / 180;
  const deltaLatitude = toRadians(to.latitude - from.latitude);
  const deltaLongitude = toRadians(to.longitude - from.longitude);
  const fromLatitude = toRadians(from.latitude);
  const toLatitude = toRadians(to.latitude);
  const a =
    Math.sin(deltaLatitude / 2) ** 2 +
    Math.cos(fromLatitude) *
      Math.cos(toLatitude) *
      Math.sin(deltaLongitude / 2) ** 2;
  return 2 * earthRadiusMiles * Math.asin(Math.min(1, Math.sqrt(a)));
}

/**
 * Every bundled place within `miles` of any centre the text resolves to.
 *
 * Returns the centres themselves as well, so a radius search is always a
 * superset of the exact-name search it replaces — narrowing the radius can
 * never lose the town the user actually typed.
 */
export function placesWithinRadius(
  text: string,
  miles: RadiusMiles,
): readonly UkPlace[] {
  const centres = resolveUkPlaces(text);
  if (centres.length === 0) return [];
  const within = places.filter((place) =>
    centres.some((centre) => distanceMiles(centre, place) <= miles),
  );
  return within;
}
