begin;

-- `job_locations` has carried `latitude`, `longitude`, and `postcode_fragment`
-- since Task 1 and nothing has ever written to them. Location matching was a
-- single ILIKE against the advert's raw text, which is wrong in both
-- directions: a search for Manchester never saw a role in Salford two miles
-- away, and a search for Bath matched Bathgate four hundred miles away.
--
-- This gives those columns a writer and adds the distance arithmetic. The place
-- rows are generated by scripts/build-uk-places.mjs from Ordnance Survey Open
-- Names and OpenStreetMap; see supabase/seed/uk-places.generated.sql for
-- provenance and licensing. Nothing here performs a geocoding request: the
-- centroids are seeded once and matched locally.

create table public.uk_places (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  normalised_name text not null check (char_length(normalised_name) between 1 and 120),
  nation text not null check (
    nation in ('England', 'Scotland', 'Wales', 'Northern Ireland')
  ),
  latitude numeric(9, 6) not null check (latitude between 49.8 and 61.0),
  longitude numeric(9, 6) not null check (longitude between -8.7 and 1.9),
  created_at timestamptz not null default now(),
  -- A name can legitimately name two settlements: there is a Bangor in Gwynedd
  -- and another in County Down. The coordinate is what makes a row unique.
  unique (normalised_name, latitude, longitude)
);

create index uk_places_normalised_idx on public.uk_places (normalised_name);
create index uk_places_bounds_idx on public.uk_places (latitude, longitude);

/**
 * Must stay identical to `normalisePlaceName` in the domain package and to
 * `normalise` in scripts/build-uk-places.mjs. All three answer "is this the
 * same place?", and a disagreement shows up as a location that matches in one
 * layer and not another.
 */
create or replace function private.normalise_place_name(value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select trim(regexp_replace(lower(unaccent_static(value)), '[^a-z0-9]+', ' ', 'g'));
$$;

-- `unaccent` is an extension and may not be installed. This does the same job
-- for the Latin-1 letters that actually occur in UK place names, and stays
-- immutable so it can be used in an index.
create or replace function public.unaccent_static(value text)
returns text
language sql
immutable
set search_path = ''
as $$
  select translate(
    value,
    'àáâãäåèéêëìíîïòóôõöùúûüýÿñçÀÁÂÃÄÅÈÉÊËÌÍÎÏÒÓÔÕÖÙÚÛÜÝÑÇ',
    'aaaaaaeeeeiiiiooooouuuuyyncAAAAAAEEEEIIIIOOOOOUUUUYNC'
  );
$$;

/**
 * Great-circle distance in miles.
 *
 * Plain trigonometry rather than PostGIS or earthdistance: neither extension is
 * installed, both would have to be enabled in every environment, and the whole
 * requirement is one distance between two points.
 */
create or replace function public.miles_between(
  from_latitude numeric,
  from_longitude numeric,
  to_latitude numeric,
  to_longitude numeric
)
returns double precision
language sql
immutable
set search_path = ''
as $$
  select 2 * 3958.8 * asin(least(1.0, sqrt(
    sin(radians(to_latitude - from_latitude) / 2) ^ 2
    + cos(radians(from_latitude))
      * cos(radians(to_latitude))
      * sin(radians(to_longitude - from_longitude) / 2) ^ 2
  )));
$$;

/**
 * Resolves advert location prose to a seeded place.
 *
 * Adverts write locations as sentences — "Leeds, West Yorkshire (hybrid)" — so
 * an equality test finds very little. The longest contained place name wins, so
 * "Newcastle upon Tyne" beats "Newcastle" on a string holding both, and the
 * space padding keeps "Bath" from matching "Bathgate".
 */
create or replace function public.resolve_uk_place(location_text text)
returns public.uk_places
language sql
stable
set search_path = ''
as $$
  select place.*
  from public.uk_places as place
  where position(
    ' ' || place.normalised_name || ' '
    in ' ' || private.normalise_place_name(location_text) || ' '
  ) > 0
  order by char_length(place.normalised_name) desc, place.name
  limit 1;
$$;

create or replace function private.set_job_location_coordinates()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  resolved public.uk_places;
begin
  -- An ingestion adapter that supplied real coordinates is more authoritative
  -- than a centroid lookup, so never overwrite what it provided.
  if new.latitude is not null and new.longitude is not null then
    return new;
  end if;
  resolved := public.resolve_uk_place(
    coalesce(nullif(new.town_city, ''), new.raw_location)
  );
  if resolved.id is not null then
    new.latitude := resolved.latitude;
    new.longitude := resolved.longitude;
    new.town_city := coalesce(nullif(new.town_city, ''), resolved.name);
    new.nation := coalesce(new.nation, resolved.nation);
  end if;
  return new;
end;
$$;

create trigger job_locations_set_coordinates
before insert or update of raw_location, town_city on public.job_locations
for each row execute function private.set_job_location_coordinates();

/**
 * Job ids with a location within `radius_miles` of any place the text names.
 *
 * A bounding box narrows the candidate rows using the plain btree index before
 * the trigonometry runs, so the exact test only ever sees a small set. The box
 * is deliberately generous — one degree of latitude is about 69 miles, and the
 * longitude degree is widened by latitude — because a box that is too tight
 * silently drops results while one that is too loose only costs a few rows.
 */
create or replace function public.jobs_within_radius(
  location_text text,
  radius_miles integer
)
returns table (job_id uuid)
language sql
stable
security definer
set search_path = ''
as $$
  with centre as (
    select place.latitude, place.longitude
    from public.uk_places as place
    where place.normalised_name = private.normalise_place_name(location_text)
       or position(
            ' ' || place.normalised_name || ' '
            in ' ' || private.normalise_place_name(location_text) || ' '
          ) > 0
    order by char_length(place.normalised_name) desc
    limit 4
  ),
  bounds as (
    select
      centre.latitude,
      centre.longitude,
      least(radius_miles, 50) / 69.0 as latitude_span,
      least(radius_miles, 50)
        / greatest(1.0, 69.0 * cos(radians(centre.latitude))) as longitude_span
    from centre
  )
  select distinct location.job_id
  from public.job_locations as location
  join bounds
    on location.latitude between bounds.latitude - bounds.latitude_span
                             and bounds.latitude + bounds.latitude_span
   and location.longitude between bounds.longitude - bounds.longitude_span
                              and bounds.longitude + bounds.longitude_span
  where location.latitude is not null
    and location.longitude is not null
    and public.miles_between(
      bounds.latitude, bounds.longitude, location.latitude, location.longitude
    ) <= least(radius_miles, 50);
$$;

alter table public.uk_places enable row level security;
alter table public.uk_places force row level security;

-- Reference data with no owner and nothing private in it. Approved users read
-- it so the client can label a radius; it is never written from the product.
create policy "approved users read uk places"
on public.uk_places for select to authenticated
using (public.has_approved_access());

grant select on public.uk_places to authenticated, service_role;

revoke all on function public.resolve_uk_place(text) from public, anon;
revoke all on function public.jobs_within_radius(text, integer) from public, anon;
revoke all on function private.normalise_place_name(text)
  from public, anon, authenticated, service_role;
revoke all on function private.set_job_location_coordinates()
  from public, anon, authenticated, service_role;

grant execute on function public.miles_between(numeric, numeric, numeric, numeric)
  to authenticated, service_role;
grant execute on function public.unaccent_static(text)
  to authenticated, service_role;
grant execute on function public.resolve_uk_place(text)
  to authenticated, service_role;
grant execute on function public.jobs_within_radius(text, integer)
  to authenticated, service_role;

commit;
